Allow merge branches from multiple remotes

diff --git a/hack/jenkins/job-configs/rktnetes-jenkins/kubernetes-build.yaml b/hack/jenkins/job-configs/rktnetes-jenkins/kubernetes-build.yaml
--- a/hack/jenkins/job-configs/rktnetes-jenkins/kubernetes-build.yaml
+++ b/hack/jenkins/job-configs/rktnetes-jenkins/kubernetes-build.yaml
@@ -12,19 +12,20 @@
             #!/bin/bash
             set -x
             set -e
-            COREOS_MERGE_BRANCHES=(rktnetes_e2e gce_coreos_rkt)
+            MERGE_BRANCHES=(euank/rktnetes_e2e coreos/gce_coreos_rkt)
 
             fail() {
               1>&2 echo "Error: $1"
               exit 1
             }
 
-            # It's okay if the remote already exists
-            git remote add coreos https://github.com/coreos/kubernetes.git || true
-            # TODO, these could be a bash arr to be easier to work with
-            for $branch in ${COREOS_MERGE_BRANCHES[@]}; do
-              git fetch coreos ${branch}:${branch} || fail "Could not fetch ${branch}"
-              git merge $branch || fail "Could not merge ${branch}"
+            for ref in ${MERGE_BRANCHES[@]}; do
+              remote=$(echo $ref | awk -F/ '{print $1}')
+              branch=$(echo $ref | awk -F/ '{print $2}')
+              # It's okay if the remote already exists
+              git remote add $remote https://github.com/${remote}/kubernetes.git || true
+              git fetch ${remote} ${branch}:${ref} || fail "Could not fetch ${ref}"
+              git merge -m "Auto-merging ${ref}" $ref || fail "Could not merge ${ref}"
             done
         - shell: 'JENKINS_BUILD_STARTED=true bash <(curl -fsS --retry 3 "https://raw.githubusercontent.com/coreos/kubernetes/rktnetes_e2e/hack/jenkins/upload-to-gcs.sh")'
         - shell: |
